### ISSUE TITLE
close time-picker onBlur after time selection

### ISSUE THREAD

**Issue by ghost** [javadbat/jb-time-input#2]
Hi Javad. Thanks for this beautiful library.  
I think it would be better to close time-picker onBlur after time selection. whenever i click on time input, the time-picker box disappears on clicking outside the box, but in case i select a time, i have to click the close button in order to close the time-picker box & it won't close on blur (clicking outside) anymore.

**Comment by javadbat** [comment]
thank you sina for your feedback i will work on it as soon as possible
