### ISSUE TITLE
Make minutes uneditable

### ISSUE THREAD

**Issue by jameswright1562** [javadbat/jb-time-input#4]
A user does not have a feature to have a greyed out :00 on the graphic, to avoid entering minutes if they don't want to. 

Also the user needs to press tab several times to jump to the next component.

**Comment by javadbat** [comment]
thank you for your feedback
I will work on them to fix the problem of tabs.
but for minute input I have some questions:
1- how do you expect minutes to be placed in value if the user did not input it? 12 or 12:00
2- how do you want the user to see his inputted value in the input box? 12 or 12:00

**Comment by jameswright1562** [comment]
Thank you for your response. I would like it to be 12 on the clock but
12:00 on the input box.

Would it also be possible to get numbers to say '06' instead of 6?

**Comment by javadbat** [comment]
yes of course

**Comment by javadbat** [comment]
first adding frontal zero to time-picker
https://github.com/javadbat/jb-time-picker/commit/54763cdabc0afcc62bbdc80b74bbe1011722d936

**Comment by javadbat** [comment]
add optional time unit
https://github.com/javadbat/jb-time-picker/commit/f55fc03009d8ead1c529f54999d2f7428a0c1a8c

**Comment by jameswright1562** [comment]
Thank you so much for this. Would it be possible to publish this to npm?

**Comment by javadbat** [comment]
ofcourse, its just need more work to do and need testing, but I will publish it as soon as possible

**Comment by javadbat** [comment]
you can use `frontalZero` and `optionalUnits` as written on documentation
